# Generated by Django 6.0.3 on 2026-03-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('food_kits_available', models.IntegerField(default=0)),
                ('medical_teams', models.IntegerField(default=0)),
                ('boats_available', models.IntegerField(default=0)),
            ],
        ),
    ]
